from classifier import NetworkClassifier
from regressor import NetworkRegressor
from autoencoder import NetworkAutoencoder
from adversarial import NetworkAdversarial
from adversarial_sequential import NetworkAdversarialSequential
from folded import NetworkFolded
from rladder import NetworkRLadder
